name: Docker Image CI



on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]



jobs:



  build:



    runs-on: ubuntu-latest



    steps:

    - uses: actions/checkout@v1

    - name: Login to DockerHub Registry

      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build the Preprocess image

      run: docker build ./mlops/preprocess --tag disha1deloitte/mlops:devops-proj_preprocess

    - name: Push the Preprocess image

      run: docker push disha1deloitte/mlops:devops-proj_preprocess

    - name: Build the Train image

      run: docker build ./mlops/training --tag disha1deloitte/mlops:devops-proj_training

    - name: Push the Train image

      run: docker push disha1deloitte/mlops:devops-proj_training

    - name: Build the Test image

      run: docker build ./mlops/testing --tag disha1deloitte/mlops:devops-proj_testing

    - name: Push the Test image

      run: docker push disha1deloitte/mlops:devops-proj_testing

